extends Node
enum LOCATIONS{DS,NSP,DR,ME,JT,NSO,VB,WG,DA,UK,CRACK_TEAM_BASE,FILE_CITY,SHORE}
enum ITEMS{X_ANTIBODY,USB_DEFEND,USB_ATTACK,USB_INTELIGENT,USB_SPEED,USB_LIFE,USB_ENERGY,USB_WILL}
var base:Dictionary={}

func _ready()->void:
	var data_base=FileAccess.open("res://data base/Base.csv",FileAccess.READ)
	var _keys= data_base.get_csv_line()
	while data_base.get_position() < data_base.get_length():
		var new_digimon_data_unconver=data_base.get_csv_line(";")
		var new_digimon_data:Array=[]
		for a in new_digimon_data_unconver:
			if a== new_digimon_data_unconver[1]:new_digimon_data+=[a]
			else:new_digimon_data+=[int(a)]
		base[new_digimon_data[0] as int]=new_digimon_data
	base.make_read_only()

const ZONES:Dictionary={
	Vector2i(0, 0): LOCATIONS.DS,
	Vector2i(0, 1): LOCATIONS.DS,
	Vector2i(0, 2): LOCATIONS.DS,
	Vector2i(0, 3): LOCATIONS.DS,
	Vector2i(0, 4): LOCATIONS.DS,
	Vector2i(0, 5): LOCATIONS.DS,
	Vector2i(0, 6): LOCATIONS.DS,
	Vector2i(0, 7): LOCATIONS.DS,
	Vector2i(1, 0): LOCATIONS.DS,
	Vector2i(1, 1): LOCATIONS.DS,
	Vector2i(1, 2): LOCATIONS.WG,
	Vector2i(1, 3): LOCATIONS.JT,
	Vector2i(1, 4): LOCATIONS.JT,
	Vector2i(1, 5): LOCATIONS.JT,
	Vector2i(1, 6): LOCATIONS.DS,
	Vector2i(1, 7): LOCATIONS.DS,
	Vector2i(2, 0): LOCATIONS.DS,
	Vector2i(2, 1): LOCATIONS.WG,
	Vector2i(2, 2): LOCATIONS.WG,
	Vector2i(2, 3): LOCATIONS.JT,
	Vector2i(2, 4): LOCATIONS.JT,
	Vector2i(2, 5): LOCATIONS.JT,
	Vector2i(2, 6): LOCATIONS.JT,
	Vector2i(2, 7): LOCATIONS.DS,
	Vector2i(3, 0): LOCATIONS.DS,
	Vector2i(3, 1): LOCATIONS.WG,
	Vector2i(3, 2): LOCATIONS.WG,
	Vector2i(3, 3): LOCATIONS.NSP,
	Vector2i(3, 4): LOCATIONS.NSP,
	Vector2i(3, 5): LOCATIONS.NSP,
	Vector2i(3, 6): LOCATIONS.NSP,
	Vector2i(3, 7): LOCATIONS.DS,
	Vector2i(4, 0): LOCATIONS.DS,
	Vector2i(4, 1): LOCATIONS.DS,
	Vector2i(4, 2): LOCATIONS.NSP,
	Vector2i(4, 3): LOCATIONS.VB,
	Vector2i(4, 4): LOCATIONS.NSP,
	Vector2i(4, 5): LOCATIONS.NSP,
	Vector2i(4, 6): LOCATIONS.NSP,
	Vector2i(4, 7): LOCATIONS.DS,
	Vector2i(5, 0): LOCATIONS.DS,
	Vector2i(5, 1): LOCATIONS.DS,
	Vector2i(5, 2): LOCATIONS.VB,
	Vector2i(5, 3): LOCATIONS.VB,
	Vector2i(5, 4): LOCATIONS.WG,
	Vector2i(5, 5): LOCATIONS.NSP,
	Vector2i(5, 6): LOCATIONS.DS,
	Vector2i(5, 7): LOCATIONS.DS,
	Vector2i(6, 0): LOCATIONS.DS,
	Vector2i(6, 1): LOCATIONS.VB,
	Vector2i(6, 2): LOCATIONS.VB,
	Vector2i(6, 3): LOCATIONS.NSO,
	Vector2i(6, 4): LOCATIONS.NSO,
	Vector2i(6, 5): LOCATIONS.DS,
	Vector2i(6, 6): LOCATIONS.DS,
	Vector2i(6, 7): LOCATIONS.DS,
	Vector2i(7, 0): LOCATIONS.DS,
	Vector2i(7, 1): LOCATIONS.NSO,
	Vector2i(7, 2): LOCATIONS.NSO,
	Vector2i(7, 3): LOCATIONS.NSO,
	Vector2i(7, 4): LOCATIONS.NSO,
	Vector2i(7, 5): LOCATIONS.DS,
	Vector2i(7, 6): LOCATIONS.DS,
	Vector2i(7, 7): LOCATIONS.DS,
	Vector2i(8, 0): LOCATIONS.DS,
	Vector2i(8, 1): LOCATIONS.VB,
	Vector2i(8, 2): LOCATIONS.NSO,
	Vector2i(8, 3): LOCATIONS.NSO,
	Vector2i(8, 4): LOCATIONS.WG,
	Vector2i(8, 5): LOCATIONS.WG,
	Vector2i(8, 6): LOCATIONS.NSP,
	Vector2i(8, 7): LOCATIONS.DS,
	Vector2i(9, 0): LOCATIONS.DS,
	Vector2i(9, 1): LOCATIONS.VB,
	Vector2i(9, 2): LOCATIONS.NSO,
	Vector2i(9, 3): LOCATIONS.DR,
	Vector2i(9, 4): LOCATIONS.DR,
	Vector2i(9, 5): LOCATIONS.WG,
	Vector2i(9, 6): LOCATIONS.NSP,
	Vector2i(9, 7): LOCATIONS.DS,
	Vector2i(10, 0): LOCATIONS.DS,
	Vector2i(10, 1): LOCATIONS.ME,
	Vector2i(10, 2): LOCATIONS.ME,
	Vector2i(10, 3): LOCATIONS.ME,
	Vector2i(10, 4): LOCATIONS.DR,
	Vector2i(10, 5): LOCATIONS.DR,
	Vector2i(10, 6): LOCATIONS.DS,
	Vector2i(10, 7): LOCATIONS.DS,
	Vector2i(11, 0): LOCATIONS.DS,
	Vector2i(11, 1): LOCATIONS.ME,
	Vector2i(11, 2): LOCATIONS.ME,
	Vector2i(11, 3): LOCATIONS.ME,
	Vector2i(11, 4): LOCATIONS.ME,
	Vector2i(11, 5): LOCATIONS.DR,
	Vector2i(11, 6): LOCATIONS.DS,
	Vector2i(11, 7): LOCATIONS.DS,
	Vector2i(12, 0): LOCATIONS.DS,
	Vector2i(12, 1): LOCATIONS.DS,
	Vector2i(12, 2): LOCATIONS.DS,
	Vector2i(12, 3): LOCATIONS.DS,
	Vector2i(12, 4): LOCATIONS.DS,
	Vector2i(12, 5): LOCATIONS.DS,
	Vector2i(12, 6): LOCATIONS.DS,
	Vector2i(12, 7): LOCATIONS.DS}
